/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Stage2 */

#ifndef _Included_Stage2
#define _Included_Stage2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Stage2
 * Method:    blep
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Stage2_blep
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
